# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "install-import"
#   createdAt: seconds:1763756938 nanos:454572572
#   expiresAt: seconds:1795292940
#   id:        bae269c9-65c0-408a-bf96-24983d946516
#

apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2025-11-21T20:28:58.454572572Z"
    init-bundle.stackrox.io/expires-at: "2026-11-21T20:29:00Z"
    init-bundle.stackrox.io/id: bae269c9-65c0-408a-bf96-24983d946516
    init-bundle.stackrox.io/name: install-import
  creationTimestamp: null
  name: collector-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0jCCAXigAwIBAgIUM80FvwaUqfDgl49Hminht8z8VuowCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM2NjQwOTc1MTQyNzcwNDExNjA4MB4XDTI1MTEyMTIwMTAwMFoXDTMwMTEy
    MDIwMTAwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM2NjQwOTc1MTQyNzcwNDExNjA4MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAEwJugsOhNSWybmLymBuOZdYMUl0vhaASt2OSVBqqdr+0cHuXr
    PD2R7MSHgWONithmjZpq8Bg5y3Urxyfrv/Z3Y6NCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLjEp6cUAK9dVZGYvALiAiY2KXyk
    MAoGCCqGSM49BAMCA0gAMEUCIDN9G20+fJUCPvGL7t9tZmoOZlRMKceIGKvdjHch
    iNc6AiEA3M5rxrfD+lxJ7z3JQqjX8g49BoEnHzREDYQQAd9jFMg=
    -----END CERTIFICATE-----
  collector-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICpDCCAkmgAwIBAgIJALmEc7IR0P51MAoGCCqGSM49BAMCMEcxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEcMBoGA1UEBRMTNjY0MDk3
    NTE0Mjc3MDQxMTYwODAeFw0yNTExMjExOTI5MDBaFw0yNjExMjEyMDI5MDBaMIGs
    MS0wKwYDVQQKEyRiYWUyNjljOS02NWMwLTQwOGEtYmY5Ni0yNDk4M2Q5NDY1MTYx
    GjAYBgNVBAsMEUNPTExFQ1RPUl9TRVJWSUNFMUAwPgYDVQQDDDdDT0xMRUNUT1Jf
    U0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMR0w
    GwYDVQQFExQxMzM2NzkzNjgwMjU4Mjc1Njk4MTBZMBMGByqGSM49AgEGCCqGSM49
    AwEHA0IABPue53rYmn+5eefuVrfMdVHo4vgapEEyPi/F7ucC/61+6Oc7WuIGu6IK
    +z1OBoCeCZEC2IiZ7oGQWIh8F6iYwUSjgbcwgbQwDgYDVR0PAQH/BAQDAgWgMB0G
    A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1Ud
    DgQWBBShmw88P7Xm1YFQqEgy9V+6MZXPWzAfBgNVHSMEGDAWgBS4xKenFACvXVWR
    mLwC4gImNil8pDA1BgNVHREELjAsghJjb2xsZWN0b3Iuc3RhY2tyb3iCFmNvbGxl
    Y3Rvci5zdGFja3JveC5zdmMwCgYIKoZIzj0EAwIDSQAwRgIhAIF8+WNdfrhpbT3C
    Dd6OZzhh3KCiDJpGg1DPnQCi+e5BAiEAsL7+5qQcI3EbHGGNVV1oGpglbow1GEqu
    QHnCHjgWHGQ=
    -----END CERTIFICATE-----
  collector-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIAu32B6lmC/PCugS0buswGCaqlWPfKxGQrcZaotB4ivxoAoGCCqGSM49
    AwEHoUQDQgAE+57netiaf7l55+5Wt8x1Ueji+BqkQTI+L8Xu5wL/rX7o5zta4ga7
    ogr7PU4GgJ4JkQLYiJnugZBYiHwXqJjBRA==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2025-11-21T20:28:58.454572572Z"
    init-bundle.stackrox.io/expires-at: "2026-11-21T20:29:00Z"
    init-bundle.stackrox.io/id: bae269c9-65c0-408a-bf96-24983d946516
    init-bundle.stackrox.io/name: install-import
  creationTimestamp: null
  name: sensor-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0jCCAXigAwIBAgIUM80FvwaUqfDgl49Hminht8z8VuowCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM2NjQwOTc1MTQyNzcwNDExNjA4MB4XDTI1MTEyMTIwMTAwMFoXDTMwMTEy
    MDIwMTAwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM2NjQwOTc1MTQyNzcwNDExNjA4MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAEwJugsOhNSWybmLymBuOZdYMUl0vhaASt2OSVBqqdr+0cHuXr
    PD2R7MSHgWONithmjZpq8Bg5y3Urxyfrv/Z3Y6NCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLjEp6cUAK9dVZGYvALiAiY2KXyk
    MAoGCCqGSM49BAMCA0gAMEUCIDN9G20+fJUCPvGL7t9tZmoOZlRMKceIGKvdjHch
    iNc6AiEA3M5rxrfD+lxJ7z3JQqjX8g49BoEnHzREDYQQAd9jFMg=
    -----END CERTIFICATE-----
  sensor-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICsjCCAligAwIBAgIId6rc7pTDK2YwCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExM2NjQwOTc1
    MTQyNzcwNDExNjA4MB4XDTI1MTEyMTE5MjkwMFoXDTI2MTEyMTIwMjkwMFowgaUx
    LTArBgNVBAoTJGJhZTI2OWM5LTY1YzAtNDA4YS1iZjk2LTI0OTgzZDk0NjUxNjEX
    MBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7BgNVBAMMNFNFTlNPUl9TRVJWSUNF
    OiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUT
    Ezg2MjI5NDczNTM4MTAzODE2NzAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQR
    XTo5Ix31zgBYRjdN8odQ+5GtcPREiIUqaV/9kGBvegESgkWw1cBQjKmE50428OTU
    jcKlGisZEEw6HwCAldRao4HOMIHLMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAU
    BggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUTfLG
    mIPeELF8z72XvGAMwjzNqZEwHwYDVR0jBBgwFoAUuMSnpxQAr11VkZi8AuICJjYp
    fKQwTAYDVR0RBEUwQ4IPc2Vuc29yLnN0YWNrcm94ghNzZW5zb3Iuc3RhY2tyb3gu
    c3ZjghtzZW5zb3Itd2ViaG9vay5zdGFja3JveC5zdmMwCgYIKoZIzj0EAwIDSAAw
    RQIhAObmsKF5YBPeSealnal4yWlY5fhLIlv6sV9T6ai5YlefAiA2Bcze31cQJAbe
    cTJNpJbbiSHhkJNDnVD0SmpXgl27Gw==
    -----END CERTIFICATE-----
  sensor-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEILOazn14J9Oo/B0Tt2fVDgioYx1ZIHvsMLjynyzI/tkpoAoGCCqGSM49
    AwEHoUQDQgAEEV06OSMd9c4AWEY3TfKHUPuRrXD0RIiFKmlf/ZBgb3oBEoJFsNXA
    UIyphOdONvDk1I3CpRorGRBMOh8AgJXUWg==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2025-11-21T20:28:58.454572572Z"
    init-bundle.stackrox.io/expires-at: "2026-11-21T20:29:00Z"
    init-bundle.stackrox.io/id: bae269c9-65c0-408a-bf96-24983d946516
    init-bundle.stackrox.io/name: install-import
  creationTimestamp: null
  name: admission-control-tls
stringData:
  admission-control-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICxDCCAmmgAwIBAgIJALyZywHaDVLKMAoGCCqGSM49BAMCMEcxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEcMBoGA1UEBRMTNjY0MDk3
    NTE0Mjc3MDQxMTYwODAeFw0yNTExMjExOTI5MDBaFw0yNjExMjEyMDI5MDBaMIG8
    MS0wKwYDVQQKEyRiYWUyNjljOS02NWMwLTQwOGEtYmY5Ni0yNDk4M2Q5NDY1MTYx
    IjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0UxSDBGBgNVBAMMP0FE
    TUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAw
    LTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTM1OTAxMTY1NTkzODA4OTQ0MTAwWTAT
    BgcqhkjOPQIBBggqhkjOPQMBBwNCAATVJyjrbOMYQT7vkZKJ/7rMaT2BFGyGO2ek
    NphxjPejM4kKCYFPTfA5mKNZekEFOmUFHdRzHW3+LODplkBjIOJso4HHMIHEMA4G
    A1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYD
    VR0TAQH/BAIwADAdBgNVHQ4EFgQUN4xnJNic2b0ntfz1u8IPaLGeaYEwHwYDVR0j
    BBgwFoAUuMSnpxQAr11VkZi8AuICJjYpfKQwRQYDVR0RBD4wPIIaYWRtaXNzaW9u
    LWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lvbi1jb250cm9sLnN0YWNrcm94LnN2
    YzAKBggqhkjOPQQDAgNJADBGAiEA+PkM1VMTHGcoeo0i8v7hTGzY1746RuUHLxxI
    P9fw+xoCIQCVnpZa3sNB6X70+Oo5zXeT5u1qCPWbmmiRfPJl4KbBjA==
    -----END CERTIFICATE-----
  admission-control-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIMkw/bd/225TiRCE+pYHmuiT+XedN+vI9z1IS/FcXzX1oAoGCCqGSM49
    AwEHoUQDQgAE1Sco62zjGEE+75GSif+6zGk9gRRshjtnpDaYcYz3ozOJCgmBT03w
    OZijWXpBBTplBR3Ucx1t/izg6ZZAYyDibA==
    -----END EC PRIVATE KEY-----
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0jCCAXigAwIBAgIUM80FvwaUqfDgl49Hminht8z8VuowCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM2NjQwOTc1MTQyNzcwNDExNjA4MB4XDTI1MTEyMTIwMTAwMFoXDTMwMTEy
    MDIwMTAwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM2NjQwOTc1MTQyNzcwNDExNjA4MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAEwJugsOhNSWybmLymBuOZdYMUl0vhaASt2OSVBqqdr+0cHuXr
    PD2R7MSHgWONithmjZpq8Bg5y3Urxyfrv/Z3Y6NCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLjEp6cUAK9dVZGYvALiAiY2KXyk
    MAoGCCqGSM49BAMCA0gAMEUCIDN9G20+fJUCPvGL7t9tZmoOZlRMKceIGKvdjHch
    iNc6AiEA3M5rxrfD+lxJ7z3JQqjX8g49BoEnHzREDYQQAd9jFMg=
    -----END CERTIFICATE-----
