apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acs-central
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bugbiteme/rh-acs-install
    targetRevision: main
    path: k8/central
  destination:
    server: https://kubernetes.default.svc
    namespace: stackrox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
  # Ensure operators are deployed and healthy before deploying central
  dependsOn:
    - name: acs-operators

