---
apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
  labels:
    name: stackrox
---
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: central
  namespace: stackrox
spec:
  central:
    exposure:
      loadBalancer:
        enabled: false
      nodePort:
        enabled: false
      route:
        enabled: true
  egress:
    connectivityPolicy: Online
  scanner:
    analyzer:
      scaling:
        autoScalingEnabled: true
        replicas: 2
        minReplicas: 2
        maxReplicas: 5
    db:
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "2000m"
    scannerComponent: Enabled

