apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: application-controller

